# Generated by Django 5.2.6 on 2025-09-18 15:03

import clinica.base.models
import localflavor.br.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocliente',
            name='cep',
            field=clinica.base.models.BRZipCodeField(max_length=9, validators=[localflavor.br.validators.BRPostalCodeValidator(), localflavor.br.validators.BRPostalCodeValidator()]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Veterinário'), (2, 'Financeiro'), (3, 'Atendimento')]),
        ),
    ]
