name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: clinica1305
          MYSQL_DATABASE: clinica_pet_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Verificar marcadores de conflito
        run: |
          set -e
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- .; then
            echo "Erro: Foram encontrados marcadores de conflito não resolvidos."
            exit 1
          fi

      - name: Instalar dependências com Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry lock
          poetry install --with dev

      - name: Aplicar migrations
        run: poetry run python manage.py migrate

      - name: Esperar MySQL subir
        run: |
          echo "Aguardando inicialização do MySQL..."
          sleep 20

      - name: Rodar testes com cobertura
        run: poetry run pytest -q --cov=clinica --cov-fail-under=82