name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Verificar marcadores de conflito
        run: |
          set -e
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- .; then
            echo "Error: Found unresolved merge conflict markers. Resolve them and push again."
            exit 1
          fi

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry lock
          poetry install --with dev

      # ✅ Novo passo: Rodar Flake8
      - name: Verificar estilo com Flake8
        run: |
          poetry run flake8 clinica --count --max-line-length=100 --statistics

      - name: Rodar testes do Django com cobertura
        run: poetry run pytest -q --cov=clinica --cov-fail-under=82